### ISSUE TITLE
not authorized to perform: cloudformation:DescribeStacks on resource

### ISSUE THREAD

**Issue by kct22aws** [aws-samples/aws-hpc-tutorials#271] opened 2022-06-22 21:24 UTC
I am going through this workshop https://www.hpcworkshops.com/ and I followed all the steps to create IAM role. But I keep ran into the following error when trying to create cluster:
 
[ec2-user@ip-172-31-37-239 ~]$ pcluster create-cluster --cluster-name hpc --cluster-configuration config.yaml{
  "message": "User: arn:aws:sts::19087152XXXX:assumed-role/S3FullAccessForEC2Ohio/i-0d87aae0ea9c6XXXX is not authorized to perform: cloudformation:DescribeStacks on resource: arn:aws:cloudformation:us-east-2:19087152XXXX:stack/hpc/* because no identity-based policy allows the cloudformation:DescribeStacks action"
}
 
How do I fix this issue?

**Comment by mhuguesaws** [comment] 2022-06-28 20:15
Closing since the issue is resolved.

**Closed** 2022-06-28 20:15 UTC
